 - name: installing required start-up tools
   hosts: all
   vars:
     curl: curl=7.74.0-1.3+deb11u3
     terraform: golang-github-hashicorp-terraform-json-dev
     wget: wget
     rsync: rsync
     golang: golang=2:1.15~1
     ansible: ansible=2.10.7+merged+base+2.10.8+dfsg-1
     vagrant: vagrant=2.2.14+dfsg-1
     packer: packer=1.6.6+ds1-2
     docker: docker=1.5-2
     ruby: ruby=1:2.7+2
     git: git=1:2.30.2-1
   become: true
   tasks:
    - name: Ansible apt update
      apt:
        update_cache: true
    - name: install multiple packages
      apt:
        name: ["{{curl}}","{{wget}}","{{rsync}}","{{ansible}}","{{docker}}","{{ruby}}","{{git}}"]
        state: present
    # terraform: terraform=1.3.6