apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-devone-to-devtwo
  namespace: devtwo
spec:
  podSelector:
    matchLabels:
      app: devapptwo
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: devoneapp

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-devone-to-devtwo
  namespace: devtwo
spec:
  podSelector:
    matchLabels:
      app: devapptwo
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: devoneapp
