{{- $secretName := print (include "keycloak-chart.fullname" .) "-admin"  }}

{{- if not (lookup "v1" "Secret" .Release.Namespace $secretName) }}
  {{- if not .Values.keycloak.adminPasswordSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ $secretName }}
  labels:
    {{- include "keycloak-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ randAlphaNum 20 | quote }}
  {{- end }}
{{- end }}