{{- range $nameSuffix, $_ := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-chart.fullname" $ }}-{{ lower $nameSuffix }}
  labels:
    {{- include "keycloak-chart.labels" $ | nindent 4 }}  
type: Opaque
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}