{{- if .Values.keycloak.clustered }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-chart.fullname" . }}-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "keycloak-chart.selectorLabels" . | nindent 4 }}
{{- end }}