apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
annotations:
rbac.authorization.kubernetes.io/autoupdate: "true"
labels:
name: ns-read-only
namespace: kube-system
rules:
- apiGroups:
- ""
resources: ["namespaces"]
verbs:
- list
