## Prometheus server ConfigMap entries
serverFiles:
  prometheus.yml:

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090",10.0.1.2:9100,10.0.1.3:9100,10.0.1.4:9100,10.0.1.5:9100,10.0.1.6:9100]
