pipeline {
    agent any
    environment {
        SERVICE_ACCOUNT_KEY = credentials('serviceaccount')
    }
    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning the repository'
                git branch: 'main', url: 'https://github.com/Chamssiddine/remote-development-environment.git'
            }
        }

        stage('Authenticate with Google Cloud') {
            steps {
                withCredentials([file(credentialsId: 'serviceaccount', variable: 'SERVICE_ACCOUNT_KEY')]) {
                    sh '''
                    gcloud auth activate-service-account --key-file=${SERVICE_ACCOUNT_KEY}
                    gcloud config set account $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
                    gcloud config set project remotedevenv-383413
                    '''
                }
            }
        }
        stage('Deploy Prometheus') {
            steps {
                dir('helm_charts/prometheus_chart') {
                    sh 'helm repo add prometheus-community https://prometheus-community.github.io/helm-charts'
                    sh 'helm upgrade --install prometheus prometheus-community/prometheus -n monitoring --create-namespace -f prometheus_values.yaml --version 19.0.0'
                }
            }
        }

        stage('Deploy Grafana') {
            steps {
                dir('helm_charts/grafana_chart') {
                    sh 'helm repo add grafana'
                    sh 'helm upgrade --install grafana grafana/grafana -n monitoring --create-namespace -f grafana_values.yaml --version 6.50.5'
                }
            }
        }

        stage('Deploy AWX Operator') {
            steps {
                dir('helm_charts/awx_chart/awx-operator') {
                    sh 'kubectl apply -k .'
                }
            }
        }

        stage('Deploy Keycloak') {
            steps {
                dir('helm_charts/keycloak_chart') {
                    sh 'helm repo add codecentric'
                    sh 'helm upgrade --install keycloak codecentric/keycloak -f keycloak_values.yaml'
                }
            }
        }
    }
}
