---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: example-awx
spec:
  web_resource_requirements:
    requests:
      cpu: 250m
      memory: 128M
  task_resource_requirements:
    requests:
      cpu: 250m
      memory: 128M
  ee_resource_requirements:
    requests:
      cpu: 200m
      memory: 64M
