apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ltb-passwd.fullname" . }}
  labels:
{{ include "ltb-passwd.labels" . | indent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ltb-passwd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ltb-passwd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- include "ltb-passwd.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.initContainers }}
      initContainers:
      {{- with .Values.initContainers }}
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "ltb-passwd.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: LDAP_SERVER
            value: ldaps://{{ include "global.server" . }}:{{ .Values.global.sslLdapPort }}
          - name: LDAP_BINDDN
            value: {{ default (include "global.bindDN" .) (.Values.ldap.bindDN) }}
          - name: LDAP_BINDPASS
            valueFrom:
              secretKeyRef:
                name: {{ template "ltb-passwd.secretName" . }}
                key: {{ default "LDAP_ADMIN_PASSWORD" (.Values.ldap.passKey) }}
          - name: LDAP_BASE_SEARCH
            value: {{ default (include "global.baseDomain" . | quote) (.Values.ldap.searchBase | quote) }}
          {{- with .Values.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or (.Values.ldap.custom) (.Values.volumeMounts) }}
          volumeMounts:
          {{- if .Values.ldap.custom }}
            - mountPath: /etc/openldap
              name: ldap-conf
          {{- end }}
          {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- if or (.Values.ldap.custom) (.Values.volumes) }}
      volumes:
      {{- if .Values.ldap.custom }}
      - name: ldap-conf
        configMap:
          name: {{ include "ltb-passwd.fullname" . }}-ldap-cm
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
